### ISSUE TITLE
Option to enable webserver and copy in web root

### ISSUE THREAD

**Issue by grahamgilbert** [macmule/AutoImagrNBI#20]
If we were to enable the web server (`/usr/sbin/apachectl start` at boot) and have an option to copy a folder of stuff to `/Library/WebServer/Documents`, we would be able to build a self contained Imagr environment. This would be useful for the usb drive option in particular.

**Comment by clburlison** [comment]
The effects of this request will hopefully be solved with https://github.com/grahamgilbert/imagr/pull/128. Instead of starting a webserver and then pointing to localhost it would then be possible to store the files where ever we wanted and configure it within the imagr_config.plist. This would even allow users to get resources off of a smb share if they wanted.

PS - that PR is almost done. Scripts have a sight variation to how they download the file that needs to be modified and then I need to test everything again.

**Comment by clburlison** [comment]
I believe this can be closed. https://github.com/grahamgilbert/imagr/pull/128

Docs: https://github.com/grahamgilbert/imagr/wiki/Creating-an-External-Drive
