### ISSUE TITLE
Use non-SIP enabled Kernel from Recovery Partition

### ISSUE THREAD

**Issue by macmule** [macmule/AutoImagrNBI#22]
As per: https://github.com/grahamgilbert/imagr/issues/122

**Comment by clburlison** [comment]
I've updated the above Imagr issue [with new information](https://github.com/grahamgilbert/imagr/issues/122#issuecomment-223826263).

My testing has verified that this is a valid request and is likely valid in AutoCasperNBI as well. Casper Imaging might be using `systemsetup` instead of `bless` which is why you've seen no reports? 

Other possibility is users aren't actually "blessing" the NBI as the target. Which would mean after imaging they return to the blessed target which in most cases is `disk0s2`.

**Comment by macmule** [comment]
After further discussions with @clburlison & @grahamgilbert, looks to not be needed.
